name = "fabric anarchy ++"
author = "Nic Venner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45a7632bc12776764aa9d0ef063e2681b26c804eaec1952ca776ce498c625337"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
