name = "fabric anarchy ++"
author = "Nic Venner"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6809fe21f25cc877aea7a0c83125361ad2f76c71a5f7837d915a4ff55db800bc"

[versions]
fabric = "0.19.2"
minecraft = "26.1.2"
